# Generated by Django 2.0.4 on 2018-06-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbcs', '0002_sbc_feitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbc',
            name='cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sbc',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbcs.Pack'),
        ),
        migrations.AddField(
            model_name='sbc',
            name='preco_pc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sbc',
            name='preco_ps4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sbc',
            name='preco_xone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sbc',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
