# Generated by Django 2.0.4 on 2018-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcs', '0004_auto_20180625_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbc',
            name='liga',
            field=models.CharField(default='', max_length=200),
        ),
    ]
