# Generated by Django 2.0.4 on 2018-06-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbcs', '0005_sbc_liga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbc_feitos',
            name='cod',
        ),
        migrations.AddField(
            model_name='sbc_feitos',
            name='sbc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sbcs.SBC'),
        ),
    ]
